name: CI/CD com Change Gate SN

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo "Construindo o app..."

  deploy-staging:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy no Staging
        run: echo "Deploy em staging aqui..."

  gate-change:
    runs-on: ubuntu-latest
    needs: deploy-staging
    steps:
      - name: Criar Change + Gate no ServiceNow
        uses: ServiceNow/servicenow-devops-change@v6.0.0
        id: change
        with:
          devops-integration-token: ${{ secrets.SN_DEVOPS_INTEGRATION_TOKEN }}
          instance-url: ${{ secrets.SN_INSTANCE_URL }}
          tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
          context-github: ${{ toJSON(github) }}
          job-name: 'gate-change'
          change-request: >-
            {
              "setCloseCode":"true",
              "autoCloseChange":false,
              "attributes":{
                "short_description":"Gate para produção",
                "description":"Aguardando aprovação da Change no ServiceNow.",
                "assignment_group":"<SYS_ID_GRUPO>",
                "implementation_plan":"Deploy após aprovação.",
                "backout_plan":"Reverter se falhar.",
                "test_plan":"Testado no staging."
              }
            }
          deployment-gate: '{"environment":"deployment_gate","jobName":"gate-change"}'
          interval: '60'
          timeout: '3600'
          abortOnChangeStepTimeout: true

      - name: Info da Change
        run: |
          echo "Change # ${{ steps.change.outputs.change-request-number }} criado."
          echo "Status: aguardando aprovação..."

  deploy-production:
    runs-on: ubuntu-latest
    needs: gate-change
    if: steps.change.outcome == 'success'
    steps:
      - name: Deploy em Produção
        run: echo "Deploy em produção liberado"
