name: Dummy Deployment com Change Gate

on:
  workflow_dispatch:

jobs:
  desenvolvimento:
    name: Desenvolvimento
    runs-on: ubuntu-latest
    steps:
      - name: Simular deploy em desenvolvimento
        run: echo "Deploy em DEV concluído!"

  homologacao:
    name: Homologação
    runs-on: ubuntu-latest
    needs: desenvolvimento
    steps:
      - name: Simular deploy em homologação
        run: echo "Deploy em HOMOLOGAÇÃO concluído!"

  deployment_gate:
    name: Criar Change com Gate
    runs-on: ubuntu-latest
    needs: homologacao
    steps:
      - name: Criar Change com Deployment Gate
        uses: ServiceNow/servicenow-devops-change@v6.0.0
        id: change
        with:
          devops-integration-token: ${{ secrets.SN_DEVOPS_INTEGRATION_TOKEN }}
          instance-url: ${{ vars.SN_INSTANCE_URL }}
          tool-id: ${{ vars.SN_ORCHESTRATION_TOOL_ID }}
          context-github: ${{ toJSON(github) }}
          job-name: 'Gate de Produção'
          change-request: >-
            {
              "setCloseCode":"true",
              "attributes":{
                "short_description":"Deploy em produção com Gate",
                "description":"Aguardando aprovação no ServiceNow",
                "assignment_group":"a715cd759f2002002920bde8132e7018",
                "implementation_plan":"Plano validado em homolog.",
                "backout_plan":"Restaurar versão anterior",
                "test_plan":"Testado em ambiente de homologação"
              }
            }
          interval: '60'
          timeout: '3600'
          deployment-gate: '{"environment":"deployment_gate","jobName":"Deploy para Produção"}'
#producao
  producao:
    name: Deploy para Produção
    needs: deployment_gate
    runs-on: ubuntu-latest
    environment: deployment_gate
    steps:
      - name: Executar deploy em produção
        run: echo "Deploy em PRODUÇÃO realizado com sucesso!"
